### PR TITLE
Record Peer latency & speed distribution & record with accurate car size fetch buckets

### LINKED ISSUE #75: Caboose limits CAR responses to 4MiB
I started adding metrics to [bifrost-gw staging](https://protocollabs.grafana.net/d/d6FxxgJ4k/bifrost-gw-staging-metrics?orgId=1&refresh=5m&from=now-6h&to=now), will be filling issues for things I discover.

Looks like a bug caused by reuse of block-related code OR could be that metric has a ceiling:

> (caboose)

This means we fail after a few blocks and never utilize Graph API to the full extent.

cc @willscott @aarshkshah1992 @aschmahmann

### PR DESCRIPTION
**Pull request by aarshkshah1992**
Closes #75  as well.

### CODE REVIEW

File: fetcher.go [hunk 1]
```diff
@@ -65,14 +65,16 @@ func (p *pool) doFetch(ctx context.Context, from string, c cid.Cid, attempt int)
 	return
 }
 
-func (p *pool) fetchResource(ctx context.Context, from string, resource string, mime string, attempt int, cb DataCallback) (err error) {
+// TODO Refactor to use a metrics collector that encapsulates block vs CAR and metrics being collected from the request making
```
Comment (willscott) [inline fetcher.go:68]: finish this sentence?

**Review by willscott — APPROVED** [review]
