### PR TITLE
retry failed requests

### LINKED ISSUE #3: fail-over data retrieval
currently if the first request fails an error is propagated upwards. instead, the library should attempt a fail-over backend as well

### PR DESCRIPTION
**Pull request by willscott**
fix #3

### CODE REVIEW

File: pool.go [hunk 1]
```diff
@@ -153,18 +158,33 @@ func (p *pool) Close() {
...
+		aff := with
+		if aff == "" {
+			aff = fmt.Sprintf("%d%s", i, c.Hash().B58String())
+		} else {
+			aff = fmt.Sprintf("%d%s", i, aff)
+		}
+		p.lk.RLock()
+		member := p.c.LocateKey([]byte(aff))
+		p.lk.RUnlock()
+		root := member.String()
```
Comment (hacdias) [inline pool.go:179]: Can't we keep this outside the loop? Probably netgligable computational complexity, but still.

Comment (willscott) [reply pool.go:179]: we want to fail-over to a different backend when the first one fails - so we re-locate a different member by putting the different retry number into the key we locate

**Review by hacdias — APPROVED** [review]
